version: '3.8'

services:
  backend:
    build: 
      context: ./Backend
      dockerfile: DockerFile
    container_name: echo_backend
    volumes:
      # Mapeamos solo el c√≥digo de la app (no todo Backend)
      - ./Backend/app:/app/app
      # Mapeamos la carpeta de datos para que las descargas persistan
      - ./data:/app/data
    # Ejecutamos uvicorn como servidor web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Frontend
      dockerfile: DockerFile
    container_name: radio_frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

